backend:
  name: git-gateway
  branch: main

site_url: https://margohudson.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/content/gallery"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Credits", name: "credits", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "articles"
    label: "Articles"
    files:
      - label: "Life Story"
        name: "life-story"
        file: "src/content/life-story.md"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "What Am I Reading"
        name: "what-am-i-reading"
        file: "src/content/what-am-i-reading.md"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Recommended Books"
        name: "recommended-books"
        file: "src/content/recommended-books.md"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Current Events"
        name: "current-events"
        file: "src/data/current-events.csv"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Past Events"
        name: "past-events"
        file: "src/content/past-events.md"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Upcoming Events"
        name: "upcoming-events"
        file: "src/data/upcoming-events.yml"
        fields:
          - label: "Upcoming Events"
            name: upcoming_events
            widget: list
            fields:
              - { label: Date, name: date, widget: date }
              - { label: Time, name: time, widget: string }
              - { label: Description, name: description, widget: string }
              - { label: Location, name: location, widget: string }
              - {
                  label: Public,
                  name: public,
                  widget: boolean,
                  required: false,
                }
      - label: "Honors"
        name: "honors"
        file: "src/content/honors.md"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
